//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        public empresas()
        {
            this.tb_usuario_empresa = new HashSet<tb_usuario_empresa>();
        }
    
        public long pk_company { get; set; }
        public string tx_cnpj { get; set; }
        public string tx_tipoinscricao { get; set; }
        public Nullable<System.DateTime> dt_data_abertura { get; set; }
        public string tx_nome_empresarial { get; set; }
        public string tx_nome_fantasia { get; set; }
        public string tx_cnae_principal { get; set; }
        public string tx_cnae_secundario { get; set; }
        public string tx_natureza_juridica { get; set; }
        public string tx_logradouro { get; set; }
        public string tx_numero { get; set; }
        public string tx_complemento { get; set; }
        public string tx_cep { get; set; }
        public string tx_bairro_distrito { get; set; }
        public string tx_municipio { get; set; }
        public string tx_uf { get; set; }
        public string tx_email { get; set; }
        public string tx_telefone { get; set; }
        public string tx_situacao_cadastral { get; set; }
        public Nullable<System.DateTime> dt_data_situacao_cadastral { get; set; }
    
        public virtual ICollection<tb_usuario_empresa> tb_usuario_empresa { get; set; }
    }
}
