//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mercanteEntities : DbContext
    {
        public mercanteEntities()
            : base("name=mercanteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_acrescimos> tb_acrescimos { get; set; }
        public virtual DbSet<tb_alteracao> tb_alteracao { get; set; }
        public virtual DbSet<tb_ce_aleatorias_consultadas> tb_ce_aleatorias_consultadas { get; set; }
        public virtual DbSet<tb_ce_dia_porto> tb_ce_dia_porto { get; set; }
        public virtual DbSet<tb_ce_mercante> tb_ce_mercante { get; set; }
        public virtual DbSet<tb_componente_frete> tb_componente_frete { get; set; }
        public virtual DbSet<tb_condicao_venda> tb_condicao_venda { get; set; }
        public virtual DbSet<tb_de_para> tb_de_para { get; set; }
        public virtual DbSet<tb_empresas_parceiras> tb_empresas_parceiras { get; set; }
        public virtual DbSet<tb_escala> tb_escala { get; set; }
        public virtual DbSet<tb_escala_empresa_parceira> tb_escala_empresa_parceira { get; set; }
        public virtual DbSet<tb_evento_conhecimento> tb_evento_conhecimento { get; set; }
        public virtual DbSet<tb_importacao> tb_importacao { get; set; }
        public virtual DbSet<tb_indice_ce> tb_indice_ce { get; set; }
        public virtual DbSet<tb_item_carga> tb_item_carga { get; set; }
        public virtual DbSet<tb_manifesto_escala> tb_manifesto_escala { get; set; }
        public virtual DbSet<tb_manifestos> tb_manifestos { get; set; }
        public virtual DbSet<tb_moeda> tb_moeda { get; set; }
        public virtual DbSet<tb_pais> tb_pais { get; set; }
        public virtual DbSet<tb_porto> tb_porto { get; set; }
        public virtual DbSet<tb_porto_procedencia> tb_porto_procedencia { get; set; }
        public virtual DbSet<tb_porto_subsequente> tb_porto_subsequente { get; set; }
        public virtual DbSet<tb_representante> tb_representante { get; set; }
        public virtual DbSet<tb_taxas_selic> tb_taxas_selic { get; set; }
        public virtual DbSet<tb_tipo_container> tb_tipo_container { get; set; }
        public virtual DbSet<tb_tipo_embalagem> tb_tipo_embalagem { get; set; }
        public virtual DbSet<tb_tipo_granel> tb_tipo_granel { get; set; }
        public virtual DbSet<tb_tipo_item> tb_tipo_item { get; set; }
        public virtual DbSet<tb_urf> tb_urf { get; set; }
        public virtual DbSet<tb_usuario_acesso> tb_usuario_acesso { get; set; }
        public virtual DbSet<tb_via_transporte> tb_via_transporte { get; set; }
    }
}
