//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tradeadvisorEntities : DbContext
    {
        public tradeadvisorEntities()
            : base("name=tradeadvisorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<empresas> empresas { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_usuario_empresa> tb_usuario_empresa { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<schema_migrations> schema_migrations { get; set; }
    }
}
