//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tfcoreEntities : DbContext
    {
        public tfcoreEntities()
            : base("name=tfcoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_adicao> tb_adicao { get; set; }
        public virtual DbSet<tb_di> tb_di { get; set; }
        public virtual DbSet<tb_empresa> tb_empresa { get; set; }
        public virtual DbSet<tb_importacao> tb_importacao { get; set; }
        public virtual DbSet<tb_importador> tb_importador { get; set; }
        public virtual DbSet<tb_mercadoria> tb_mercadoria { get; set; }
        public virtual DbSet<tb_taxas_selic> tb_taxas_selic { get; set; }
        public virtual DbSet<tb_tipo_empresa> tb_tipo_empresa { get; set; }
        public virtual DbSet<tb_urf> tb_urf { get; set; }
        public virtual DbSet<vw_pesquisa> vw_pesquisa { get; set; }
        public virtual DbSet<tb_uf> tb_uf { get; set; }
    }
}
