//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ncmrfEntities : DbContext
    {
        public ncmrfEntities()
            : base("name=ncmrfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vw_ncm_full> vw_ncm_full { get; set; }
        public virtual DbSet<vw_ncm_full_15a> vw_ncm_full_15a { get; set; }
        public virtual DbSet<tb_ncmrf_full_15A> tb_ncmrf_full_15A { get; set; }
        public virtual DbSet<tb_ncm_computada> tb_ncm_computada { get; set; }
    }
}
