//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_adicao
    {
        public tb_adicao()
        {
            this.tb_mercadoria = new HashSet<tb_mercadoria>();
        }
    
        public long pk_adicao { get; set; }
        public long fk_di { get; set; }
        public string tx_ncm { get; set; }
        public decimal vl_ii { get; set; }
        public decimal vl_ipi { get; set; }
        public decimal vl_cofins { get; set; }
        public string tx_condicaoVendaIncoterm { get; set; }
        public string tx_condicaoVendaMoedaCodigo { get; set; }
        public string tx_condicaoVendaMoedaNome { get; set; }
        public Nullable<decimal> vl_condicaoVendaValorMoeda { get; set; }
        public string tx_dadosCargaPaisProcedenciaCodigo { get; set; }
        public string tx_dadosCargaPaisProcedenciaNome { get; set; }
        public string tx_dadosCargaUrfEntradaCodigo { get; set; }
        public string tx_dadosCargaUrfEntradaNome { get; set; }
        public string tx_freteMoedaNegociadaCodigo { get; set; }
        public string tx_freteMoedaNegociadaNome { get; set; }
        public decimal vl_freteValorMoedaNegociada { get; set; }
        public decimal vl_freteValorReais { get; set; }
        public string tx_numeroAdicao { get; set; }
        public decimal vl_iiDevido { get; set; }
        public decimal vl_iiRecolher { get; set; }
        public decimal vl_ipiDevido { get; set; }
        public decimal vl_ipiRecolher { get; set; }
        public decimal vl_pisDevido { get; set; }
        public decimal vl_pisRecolher { get; set; }
        public decimal vl_cofinsDevido { get; set; }
        public decimal vl_cofinsRecolher { get; set; }
        public decimal vl_pis { get; set; }
        public string nr_li { get; set; }
        public string tx_fabricanteNome { get; set; }
        public string tx_fornecedorNome { get; set; }
        public string tx_iiFundamentoLegalCodigo { get; set; }
        public string tx_iiFundamentoLegalNome { get; set; }
        public decimal vl_condicaoVendaValorReais { get; set; }
        public string tx_fabricanteCidade { get; set; }
        public string tx_fabricantePais { get; set; }
        public string tx_fabricanteComplemento { get; set; }
        public string tx_fabricanteEstado { get; set; }
        public string tx_fabricanteLogradouro { get; set; }
        public string tx_fabricanteNumero { get; set; }
        public string tx_fornecedorCidade { get; set; }
        public string tx_fornecedorPais { get; set; }
        public string tx_fornecedorComplemento { get; set; }
        public string tx_fornecedorEstado { get; set; }
        public string tx_fornecedorLogradouro { get; set; }
        public string tx_fornecedorNumero { get; set; }
        public Nullable<decimal> vl_dadosMercadoriaPesoLiquido { get; set; }
        public Nullable<decimal> vl_seguroValorReais { get; set; }
        public Nullable<decimal> vl_valorReaisSeguroInternacional { get; set; }
        public Nullable<decimal> vl_acrescimoValorReais { get; set; }
        public string tx_acrescimoDenominacao { get; set; }
        public string tx_acrescimoCodigo { get; set; }
        public decimal iiBaseCalculo { get; set; }
        public decimal pisCofinsBaseCalculoValor { get; set; }
    
        public virtual tb_di tb_di { get; set; }
        public virtual ICollection<tb_mercadoria> tb_mercadoria { get; set; }
    }
}
