//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ce_aleatorias_consultadas
    {
        public long pk_ce_aleatoria { get; set; }
        public string nrcemercanteconsultada { get; set; }
        public System.DateTime dtconsulta { get; set; }
        public string valido { get; set; }
    }
}
