//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_componente_frete
    {
        public long pk_componente_frete { get; set; }
        public long fk_ce_mercante { get; set; }
        public string tipo_componente { get; set; }
        public double valor { get; set; }
        public string moeda { get; set; }
        public double cotacao { get; set; }
        public string recolhimento { get; set; }
    }
}
