//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ce_dia_porto
    {
        public long pk_nr_ce_dia_porto { get; set; }
        public long fk_porto { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> conhecimentos_longo_curso_importacao_convencional { get; set; }
        public Nullable<int> conhecimentos_longo_curso_importacao_desconsolidacao { get; set; }
        public Nullable<int> manifestos_longo_curso_descosolidacao { get; set; }
    
        public virtual tb_porto tb_porto { get; set; }
    }
}
