//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_di
    {
        public tb_di()
        {
            this.tb_adicao = new HashSet<tb_adicao>();
        }
    
        public long pk_di { get; set; }
        public string tx_cnpj { get; set; }
        public System.DateTime dt_registro { get; set; }
        public string nr_di { get; set; }
        public int nu_totalAdicoes { get; set; }
        public decimal vl_taxaSicomex { get; set; }
        public string tx_cargaPaisProcedenciaNome { get; set; }
        public string tx_cargaUrfEntradaNome { get; set; }
        public Nullable<System.DateTime> dt_dataDesembaraco { get; set; }
        public decimal vl_freteTotalDolares { get; set; }
        public decimal vl_freteTotalReais { get; set; }
        public string tx_importadorCpfRepresentanteLegal { get; set; }
        public string tx_importadorNome { get; set; }
        public string tx_importadorNomeRepresentanteLegal { get; set; }
        public string tx_urfDespachoNome { get; set; }
        public string tx_viaTransporteNome { get; set; }
        public string tx_codigoTipoEmbalagem { get; set; }
        public string tx_codigoNomeEmbalagem { get; set; }
        public Nullable<decimal> nu_quantidadeVolume { get; set; }
        public Nullable<decimal> vl_cargaPesoBruto { get; set; }
        public Nullable<decimal> vl_cargaPesoLiquido { get; set; }
        public string tx_canalSelecaoParametrizada { get; set; }
        public Nullable<decimal> vl_seguroTotalDolares { get; set; }
        public Nullable<decimal> vl_seguroTotalReais { get; set; }
    
        public virtual ICollection<tb_adicao> tb_adicao { get; set; }
    }
}
