//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_de_para
    {
        public long pk_de_para { get; set; }
        public string cd_chave { get; set; }
        public string nm_descricao { get; set; }
        public string tp_tipo { get; set; }
    }
}
