//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empresa
    {
        public tb_empresa()
        {
            this.tb_usuario_empresa = new HashSet<tb_usuario_empresa>();
        }
    
        public long pk_empresa { get; set; }
        public string razao_social { get; set; }
        public string end_rua { get; set; }
        public string end_numero { get; set; }
        public string end_bairro { get; set; }
        public string end_cep { get; set; }
        public string end_municipio { get; set; }
        public string end_uf { get; set; }
        public Nullable<bool> importador { get; set; }
        public Nullable<bool> exportador { get; set; }
        public string cnpj { get; set; }
    
        public virtual ICollection<tb_usuario_empresa> tb_usuario_empresa { get; set; }
    }
}
