//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_evento_conhecimento
    {
        public long pk_evento_ce { get; set; }
        public long fk_ce_mercante { get; set; }
        public string modalidade { get; set; }
        public string motivo { get; set; }
        public Nullable<double> peso_liquido { get; set; }
        public Nullable<double> valor_frete { get; set; }
        public Nullable<double> valor_afrmm { get; set; }
        public Nullable<double> valor_conta_fundo { get; set; }
        public Nullable<double> valor_conta_espec { get; set; }
        public Nullable<double> valor_vinculado { get; set; }
        public Nullable<System.DateTime> data_evento { get; set; }
    }
}
