//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empresa
    {
        public long pk_empresa { get; set; }
        public string tx_nomefantasia { get; set; }
        public string tx_cidade { get; set; }
        public string cd_cidade { get; set; }
        public string tx_pais { get; set; }
        public string cd_pais { get; set; }
        public string tx_complemento { get; set; }
        public string tx_estado { get; set; }
        public string cd_estado { get; set; }
        public string tx_logradouro { get; set; }
        public string tx_numero { get; set; }
        public long fk_tipo_empresa { get; set; }
    
        public virtual tb_tipo_empresa tb_tipo_empresa { get; set; }
    }
}
