//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_escala
    {
        public tb_escala()
        {
            this.tb_porto_procedencia = new HashSet<tb_porto_procedencia>();
            this.tb_porto_subsequente = new HashSet<tb_porto_subsequente>();
        }
    
        public long pk_escala { get; set; }
        public System.DateTime dt_previsao_atracacao { get; set; }
        public System.DateTime dt_efetiva_atracacao { get; set; }
        public System.DateTime dt_previsao_desatracacao { get; set; }
        public System.DateTime dt_efetiva_desatracacao { get; set; }
        public string nr_escala { get; set; }
        public string cd_ag_navegacao { get; set; }
        public string nm_ag_navegacao { get; set; }
        public string cd_porto_escala { get; set; }
        public string nm_porto_escala { get; set; }
        public string cd_embarcacao { get; set; }
        public string nm_embarcacao { get; set; }
        public string num_viagem_armador { get; set; }
        public string tipo_operacao { get; set; }
        public string bandeira_embarcacao { get; set; }
        public string responsavel_embarcacao { get; set; }
        public string cd_empresa_navegacao { get; set; }
        public string nm_empresa_navegacao { get; set; }
        public string nacionalidade_transportador { get; set; }
    
        public virtual ICollection<tb_porto_procedencia> tb_porto_procedencia { get; set; }
        public virtual ICollection<tb_porto_subsequente> tb_porto_subsequente { get; set; }
    }
}
