//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_importacao
    {
        public long pk_importacao { get; set; }
        public System.DateTime dt_inicio { get; set; }
        public Nullable<System.DateTime> dt_fim { get; set; }
        public string bl_sucesso { get; set; }
        public System.DateTime dt_consulta { get; set; }
        public long fk_representante { get; set; }
    }
}
