//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_indice_ce
    {
        public long pk_indice_ce { get; set; }
        public long fk_importacao { get; set; }
        public System.DateTime dtoperacao { get; set; }
        public string nrcemercante { get; set; }
        public string nrblconhecimento { get; set; }
        public string nrmanifesto { get; set; }
        public string cdembarcacao { get; set; }
        public string nmembarcacao { get; set; }
        public string cdportoorigem { get; set; }
        public string cdportodestino { get; set; }
        public Nullable<bool> consultado { get; set; }
    }
}
