//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_importacao
    {
        public long pk_importacao { get; set; }
        public string nr_cnpj { get; set; }
        public System.DateTime dt_dtUltimaPesquisa { get; set; }
    }
}
