//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_mercadoria
    {
        public long pk_mercadoria { get; set; }
        public long fk_adicao { get; set; }
        public string tx_unidadeMedida { get; set; }
        public string tx_descricaoMercadoria { get; set; }
        public string nr_numeroSequenciaItem { get; set; }
        public decimal nu_quantidade { get; set; }
        public decimal vl_valorTotalCondicaoVenda { get; set; }
        public Nullable<decimal> vl_valorUnitario { get; set; }
    
        public virtual tb_adicao tb_adicao { get; set; }
    }
}
