//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ncm_computada
    {
        public string tx_ncm { get; set; }
        public string tx_ncm_desc { get; set; }
        public Nullable<double> vl_cif_tot_us { get; set; }
        public Nullable<int> vl_ift { get; set; }
    }
}
