//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ncm_aliq
    {
        public string CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public string UNIDADE_MEDIDA { get; set; }
        public string ALIQUOTA_II { get; set; }
        public string ALIQUOTA_II_MERCOSUL { get; set; }
        public string ALIQUOTA_IPI { get; set; }
        public string ALIQUOTA_PIS_ADVAL { get; set; }
        public string ALIQUOTA_COFINS_ADVAL { get; set; }
        public int pk_ncm_aliq { get; set; }
    }
}
