//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ncmrf_full_14A
    {
        public string nr_ordem { get; set; }
        public string id_mes_ano { get; set; }
        public string mes_ano { get; set; }
        public string ncm { get; set; }
        public string descricao_ncm { get; set; }
        public string codigo_pais_origem { get; set; }
        public string pais_origem { get; set; }
        public string codigo_pais_aquisicao { get; set; }
        public string pais_aquisicao { get; set; }
        public Nullable<int> codigo_unidade_medida_estatistica { get; set; }
        public string unidade_medida_estatistica { get; set; }
        public string unidade_comercializacao { get; set; }
        public string descricao_detalhada_produto { get; set; }
        public Nullable<double> quantidade_estatistica { get; set; }
        public Nullable<double> peso_liquido_kg { get; set; }
        public Nullable<double> valor_fob_dolar { get; set; }
        public Nullable<double> valor_frete_dolar { get; set; }
        public Nullable<double> valor_seguro_dolar { get; set; }
        public Nullable<double> valor_unidade_produto_dolar { get; set; }
        public Nullable<double> quantidade_comercializada_produto { get; set; }
        public Nullable<double> valor_total_produto_dolar { get; set; }
        public Nullable<System.DateTime> data_ordem { get; set; }
        public long pk_ncmrf_14a { get; set; }
    }
}
