//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_porto_subsequente
    {
        public long pk_porto_subsequente { get; set; }
        public long fk_escala { get; set; }
        public long fk_porto { get; set; }
        public System.DateTime dt_previsao_atracacao { get; set; }
    
        public virtual tb_escala tb_escala { get; set; }
        public virtual tb_porto tb_porto { get; set; }
    }
}
