//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_porto
    {
        public tb_porto()
        {
            this.tb_ce_dia_porto = new HashSet<tb_ce_dia_porto>();
            this.tb_porto_procedencia = new HashSet<tb_porto_procedencia>();
            this.tb_porto_subsequente = new HashSet<tb_porto_subsequente>();
        }
    
        public long pk_porto { get; set; }
        public string cd_porto { get; set; }
        public string nm_porto { get; set; }
    
        public virtual ICollection<tb_ce_dia_porto> tb_ce_dia_porto { get; set; }
        public virtual ICollection<tb_porto_procedencia> tb_porto_procedencia { get; set; }
        public virtual ICollection<tb_porto_subsequente> tb_porto_subsequente { get; set; }
    }
}
