//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_representante
    {
        public long pk_representante { get; set; }
        public string tx_cpf { get; set; }
        public string tx_senha { get; set; }
        public string nm_certificado { get; set; }
        public bool senha_valida { get; set; }
    }
}
