//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_empresa
    {
        public tb_tipo_empresa()
        {
            this.tb_empresa = new HashSet<tb_empresa>();
        }
    
        public long pk_tipo_empresa { get; set; }
        public string tx_descricao { get; set; }
    
        public virtual ICollection<tb_empresa> tb_empresa { get; set; }
    }
}
