//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_taxas_selic
    {
        public long pk_tx_selic { get; set; }
        public System.DateTime dt_taxa { get; set; }
        public decimal vl_taxa { get; set; }
        public System.DateTime dt_consulta { get; set; }
    }
}
