//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_empresa
    {
        public long pk_usuario_empresa { get; set; }
        public long fk_empresa { get; set; }
        public long fk_usuario { get; set; }
    
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
