//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.tb_usuario_empresa = new HashSet<tb_usuario_empresa>();
        }
    
        public long pk_usuario { get; set; }
        public string tx_nome { get; set; }
        public string tx_cpf { get; set; }
        public string tx_rg { get; set; }
        public string tx_logradouro { get; set; }
        public string tx_numero { get; set; }
        public string tx_complemento { get; set; }
        public string tx_bairro { get; set; }
        public string tx_cep { get; set; }
        public string tx_municipio { get; set; }
        public Nullable<long> fk_uf { get; set; }
        public string tx_email { get; set; }
        public string tx_telefone_casa { get; set; }
        public string tx_telefone_celular { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public Nullable<bool> bl_sexo { get; set; }
        public string tx_senha { get; set; }
    
        public virtual ICollection<tb_usuario_empresa> tb_usuario_empresa { get; set; }
    }
}
